"""
upload_slider_images.py
Upload tất cả ảnh từ "Ảnh Đã Xử Lý SEO" lên WordPress Media Library
rồi tự động cập nhật $slider_images trong template trang chủ live của plugin.
"""
import base64
import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────
BASE_DIR   = Path(r"D:\.thongtaccongquangninh")
IMG_DIR    = BASE_DIR / "Ảnh Đã Xử Lý SEO"
PHP_FILE   = BASE_DIR / "tools" / "wp-plugins" / "ttcqn-home-emergency-renderer" / "templates" / "page-home-direct.php"
LOG_FILE   = BASE_DIR / "logs" / "upload_slider_images.json"
WP_BASE    = "https://thongtaccongquangninh.com"

ENV_PATHS = [
    BASE_DIR / ".env",
    Path(r"C:\Users\DELL\Documents\Codex\2026-04-28\chatgpt-apps-plugin-chatgpt-apps-openai\.env"),
]

# ── Alt text & Caption theo prefix ─────────────────────────────────────────
ALT_MAP = {
    "tho-thong-tac-cong":  "Thợ thông tắc cống tại Quảng Ninh - Công ty Môi Trường Đô Thị Số 1",
    "tho-thong-bon-cau":   "Thợ thông tắc bồn cầu tại Quảng Ninh không đục phá",
    "tho-thong-chau-rua":  "Thợ thông tắc chậu rửa tại Quảng Ninh nhanh chóng",
    "tho-nao-vet-ho-ga":   "Thợ nạo vét hố ga tại Quảng Ninh đúng kỹ thuật",
    "tho-xu-ly-mui-hoi":   "Thợ xử lý mùi hôi nhà vệ sinh tại Quảng Ninh",
    "xe-hut---cong-ty-kcn":"Xe hút bể phốt cho công ty, khu công nghiệp tại Quảng Ninh",
    "xe-hut---ho-gia-dinh":"Xe hút bể phốt hộ gia đình tại Quảng Ninh",
}
CAP_MAP = {
    "tho-thong-tac-cong":  "Xử Lý Cống Tắc Tại Nhà - Quảng Ninh",
    "tho-thong-bon-cau":   "Thông Tắc Bồn Cầu Không Đục Phá",
    "tho-thong-chau-rua":  "Thông Tắc Chậu Rửa Tại Quảng Ninh",
    "tho-nao-vet-ho-ga":   "Nạo Vét Hố Ga Đúng Kỹ Thuật",
    "tho-xu-ly-mui-hoi":   "Xử Lý Mùi Hôi Nhà Vệ Sinh",
    "xe-hut---cong-ty-kcn":"Xe Hút Bể Phốt KCN Quảng Ninh",
    "xe-hut---ho-gia-dinh":"Xe Hút Bể Phốt Hộ Gia Đình",
}

def get_prefix(filename: str) -> str | None:
    for p in ALT_MAP:
        if filename.startswith(p):
            return p
    return None

# ── Helpers ─────────────────────────────────────────────────────────────────
def parse_env(path: Path) -> dict:
    env = {}
    if not path or not path.exists():
        return env
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\s*([^#=\s]+)\s*=\s*(.*)\s*$", line)
        if m:
            env[m.group(1)] = m.group(2).strip().strip("\"'")
    return env

def wp(auth, path, method="GET", body=None, headers=None):
    req = urllib.request.Request(
        f"{WP_BASE}/wp-json{path}",
        data=body, method=method,
        headers={"Authorization": auth, "User-Agent": "TTCQN-Slider", **(headers or {})},
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            raw = r.read()
            if "application/json" in r.headers.get("Content-Type", ""):
                return json.loads(raw.decode("utf-8-sig") or "{}")
            return raw
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"WP {e.code} {path}: {e.read().decode('utf-8', errors='replace')[:300]}")

# ── Upload 1 ảnh ─────────────────────────────────────────────────────────────
def upload_image(auth, img_path: Path) -> dict:
    prefix  = get_prefix(img_path.name)
    alt     = ALT_MAP.get(prefix, "Dịch vụ môi trường Quảng Ninh")
    caption = CAP_MAP.get(prefix, "Dịch vụ môi trường Quảng Ninh")

    # Upload
    media = wp(auth, "/wp/v2/media", method="POST",
               body=img_path.read_bytes(),
               headers={"Content-Type": "image/webp",
                        "Content-Disposition": f'attachment; filename="{img_path.name}"'})

    media_id  = media["id"]
    media_url = media["source_url"]

    # Cập nhật alt + caption
    wp(auth, f"/wp/v2/media/{media_id}", method="POST",
       body=json.dumps({"alt_text": alt, "caption": caption, "title": caption}).encode(),
       headers={"Content-Type": "application/json"})

    return {"file": img_path.name, "id": media_id, "url": media_url, "alt": alt, "caption": caption}

# ── Cập nhật PHP file ────────────────────────────────────────────────────────
def update_php_slider(uploads: list[dict]):
    php = PHP_FILE.read_text(encoding="utf-8-sig")

    # Build new $slider_images block
    lines = ["// === SLIDER IMAGES - Auto-generated by upload_slider_images.py ==="]
    lines.append("$slider_images = [")
    for u in uploads:
        alt = u["alt"].replace("'", "\\'")
        lines.append(f"    ['src' => '{u['url']}', 'alt' => '{alt}'],")
    lines.append("];")
    new_block = "\n".join(lines)

    # Pattern khớp từ comment "Slider images" đến dòng đóng array
    pattern = r"// Slider images.*?^\$slider_images\s*=\s*\[.*?\];"
    if re.search(pattern, php, re.DOTALL | re.MULTILINE):
        php = re.sub(pattern, new_block, php, flags=re.DOTALL | re.MULTILINE)
    else:
        # Fallback: thay thế toàn bộ block $slider_images = [...]
        pattern2 = r"\$slider_images\s*=\s*\[.*?\];"
        if re.search(pattern2, php, re.DOTALL):
            php = re.sub(pattern2, new_block, php, count=1, flags=re.DOTALL)
        else:
            print("⚠️  Không tìm thấy $slider_images trong PHP file — cần cập nhật thủ công.")
            return False

    PHP_FILE.write_text(php, encoding="utf-8-sig")
    print(f"✅ Đã cập nhật $slider_images trong {PHP_FILE.name} ({len(uploads)} ảnh)")
    return True

# ── Main ─────────────────────────────────────────────────────────────────────
def main():
    # 1. Load .env
    env = {}
    for p in ENV_PATHS:
        env = parse_env(Path(p))
        if env:
            print(f"✅ Đọc .env từ: {p}")
            break

    if not env.get("WP_USERNAME") or not env.get("WP_APP_PASSWORD"):
        print("❌ Không tìm thấy WP_USERNAME / WP_APP_PASSWORD trong .env")
        print("   Tạo file D:\\.thongtaccongquangninh\\.env với nội dung:")
        print("   WP_USERNAME=admin")
        print("   WP_APP_PASSWORD=xxxx xxxx xxxx xxxx")
        return

    auth = "Basic " + base64.b64encode(
        f"{env['WP_USERNAME']}:{env['WP_APP_PASSWORD']}".encode()
    ).decode()

    # 2. Lấy danh sách ảnh
    images = sorted(IMG_DIR.glob("*.webp"))
    if not images:
        print(f"❌ Không tìm thấy ảnh .webp trong: {IMG_DIR}")
        return
    print(f"📂 Tìm thấy {len(images)} ảnh trong: {IMG_DIR.name}")

    # 3. Kiểm tra ảnh đã upload chưa (tránh duplicate)
    print("🔍 Kiểm tra ảnh đã tồn tại trên WordPress...")
    try:
        existing = wp(auth, "/wp/v2/media?per_page=100&search=tho-&context=edit")
        existing += wp(auth, "/wp/v2/media?per_page=100&search=xe-hut&context=edit")
        existing_filenames = {
            Path(m.get("source_url", "")).name for m in existing
            if isinstance(m, dict)
        }
    except Exception as e:
        print(f"⚠️  Không kiểm tra được media library: {e}")
        existing_filenames = set()

    # 4. Upload từng ảnh
    uploads = []
    for img in images:
        if img.name in existing_filenames:
            print(f"   ⏭  Đã tồn tại: {img.name}")
            # Lấy URL từ WordPress
            try:
                results = wp(auth, f"/wp/v2/media?search={img.stem}&per_page=10")
                for r in results:
                    if Path(r.get("source_url","")).name == img.name:
                        prefix = get_prefix(img.name)
                        uploads.append({
                            "file": img.name,
                            "id": r["id"],
                            "url": r["source_url"],
                            "alt": ALT_MAP.get(prefix, "Dịch vụ môi trường Quảng Ninh"),
                            "caption": CAP_MAP.get(prefix, ""),
                        })
                        break
            except Exception:
                pass
            continue

        try:
            result = upload_image(auth, img)
            uploads.append(result)
            print(f"   ✅ Uploaded: {img.name} → ID {result['id']}")
        except Exception as e:
            print(f"   ❌ Lỗi {img.name}: {e}")

    if not uploads:
        print("❌ Không có ảnh nào được upload thành công.")
        return

    # 5. Cập nhật PHP file
    print(f"\n📝 Cập nhật slider trong {PHP_FILE.relative_to(BASE_DIR)}...")
    update_php_slider(uploads)

    # 6. Ghi log
    LOG_FILE.parent.mkdir(exist_ok=True)
    LOG_FILE.write_text(
        json.dumps({"total": len(uploads), "uploads": uploads}, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )
    print(f"\n🎉 XONG! {len(uploads)} ảnh trong slider.")
    print(f"📋 Log: {LOG_FILE}")
    print("\n⚡ Bước tiếp theo:")
    print("   1. Pack lại plugin ttcqn-home-emergency-renderer")
    print("   2. Upload plugin bằng tools/upload_home_emergency_renderer_plugin.mjs")

if __name__ == "__main__":
    main()
